# Generated by Django 4.2.15 on 2026-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypoints',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
