# Generated by Django 4.2.15 on 2026-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fix_missing_expense_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensereason',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensereason',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
