# Generated by Django 4.2.15 on 2026-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_expense_access_id_expense_update_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('windows', 'Windows')], max_length=20)),
                ('version', models.CharField(max_length=40)),
                ('build', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='app_updates/')),
                ('required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform', '-build', '-id'],
                'indexes': [models.Index(fields=['platform', 'is_active', '-build'], name='dashboard_a_platfor_786b2f_idx')],
            },
        ),
    ]
