# Generated by Django 4.2.15 on 2025-12-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='رصيد العميل الحالي (موجب: عليه / سالب: له)', max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الرصيد السابق بين التاجر والعميل', max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='رصيد المورّد الحالي (موجب: له / سالب: عليه)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الرصيد السابق بين التاجر والمورّد', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_customer_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('store', 'phone'), name='unique_customer_phone_per_store'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_supplier_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('store', 'phone'), name='unique_supplier_phone_per_store'),
        ),
    ]
