# Generated by Django 4.2.15 on 2025-12-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_balance_customer_opening_balance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_name_per_store',
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_phone_per_store',
        ),
        migrations.RemoveConstraint(
            model_name='supplier',
            name='unique_supplier_name_per_store',
        ),
        migrations.RemoveConstraint(
            model_name='supplier',
            name='unique_supplier_phone_per_store',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='balance',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الرصيد السابق بين التاجر والمورّد', max_digits=10),
        ),
    ]
