# Generated by Django 4.2.15 on 2025-12-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_balance_customer_opening_balance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplier',
            name='unique_supplier_phone_per_store',
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('store', 'phone'), name='unique_supplier_phone_per_store_when_exists'),
        ),
    ]
