# Generated by Django 4.2.15 on 2026-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_supplier_unique_supplier_phone_per_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='customer_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
