# Generated by Django 4.2.15 on 2026-01-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pointstransaction_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='access_id',
            field=models.IntegerField(blank=True, help_text='رقم السجل في جدول الكاش باك ببرنامج المحاسبة', null=True),
        ),
    ]
