# Generated by Django 4.2.15 on 2026-01-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pointstransaction_access_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
