# Generated by Django 4.2.15 on 2026-01-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_cashback_percentage'),
        ('accounts', '0008_alter_pointstransaction_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(max_length=64, unique=True)),
                ('last_notification_id', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_clients', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('web', 'Web'), ('accounting', 'Accounting'), ('both', 'Web + Accounting')], default='both', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('is_global', models.BooleanField(default=False, help_text='إذا مفعّل، الإشعار يوصل للجميع حسب القناة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('require_ack', models.BooleanField(default=False, help_text='هل يجب تأكيد قراءة الإشعار؟')),
                ('version_min', models.CharField(blank=True, help_text='أدنى إصدار برنامج يظهر له الإشعار', max_length=20, null=True)),
                ('target_accounting_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to='accounts.accountingclient')),
                ('target_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to='stores.store')),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
