# Generated by Django 4.2.15 on 2026-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_appupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appupdate',
            name='prices_version',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appupdate',
            name='version',
            field=models.DateField(),
        ),
    ]
