# Generated by Django 4.2.15 on 2026-02-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_appupdate_prices_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appupdate',
            name='prices_version',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appupdate',
            name='version',
            field=models.PositiveIntegerField(),
        ),
    ]
