# Generated by Django 4.2.15 on 2026-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_appupdate_prices_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingclient',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appupdate',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appupdate',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountingclient',
            name='access_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='access_id',
            field=models.BigIntegerField(blank=True, help_text='رقم السجل في جدول الكاش باك ببرنامج المحاسبة', null=True),
        ),
    ]
