# Generated by Django 4.2.15 on 2026-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_deletesync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ط±طµظٹط¯ ط§ظ„ط¹ظ…ظٹظ„ ط§ظ„ط\xadط§ظ„ظٹ (ظ…ظˆط¬ط¨: ط¹ظ„ظٹظ‡ / ط³ط§ظ„ط¨: ظ„ظ‡)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ط§ظ„ط±طµظٹط¯ ط§ظ„ط³ط§ط¨ظ‚ ط¨ظٹظ† ط§ظ„طھط§ط¬ط± ظˆط§ظ„ط¹ظ…ظٹظ„', max_digits=12),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='is_global',
            field=models.BooleanField(default=False, help_text='ط¥ط°ط§ ظ…ظپط¹ظ‘ظ„طŒ ط§ظ„ط¥ط´ط¹ط§ط± ظٹظˆطµظ„ ظ„ظ„ط¬ظ…ظٹط¹ ط\xadط³ط¨ ط§ظ„ظ‚ظ†ط§ط©'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='require_ack',
            field=models.BooleanField(default=False, help_text='ظ‡ظ„ ظٹط¬ط¨ طھط£ظƒظٹط¯ ظ‚ط±ط§ط،ط© ط§ظ„ط¥ط´ط¹ط§ط±طں'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='version_min',
            field=models.CharField(blank=True, help_text='ط£ط¯ظ†ظ‰ ط¥طµط¯ط§ط± ط¨ط±ظ†ط§ظ…ط¬ ظٹط¸ظ‡ط± ظ„ظ‡ ط§ظ„ط¥ط´ط¹ط§ط±', max_length=20, null=True),
        ),
    ]
