# Generated by Django 4.2.15 on 2026-05-14 10:04

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_warehouse_access_id_warehouse_update_time'),
        ('accounts', '0015_alter_customer_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.BigIntegerField(blank=True, null=True)),
                ('access_id', models.BigIntegerField(blank=True, null=True)),
                ('identifier', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('permissions', models.JSONField(default=accounts.models.default_store_user_permissions)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='stores.store')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_users', to='stores.warehouse')),
            ],
            options={
                'ordering': ['store_id', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='storeuser',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_store_user_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='storeuser',
            constraint=models.UniqueConstraint(fields=('store', 'identifier'), name='unique_store_user_identifier_per_store'),
        ),
    ]
