# Generated by Django 4.2.15 on 2026-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_storeuser_storeuser_unique_store_user_name_per_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
