# Generated by Django 4.2.15 on 2026-05-14 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_storeuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
