# Generated by Django 4.2.15 on 2026-06-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_storeuser_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appupdate',
            name='prices_version',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appupdate',
            name='version',
            field=models.PositiveIntegerField(),
        ),
    ]
