# Generated by Django 4.2.15 on 2026-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_fix_appupdate_date_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
