# Generated by Django 4.2.15 on 2025-12-12 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('mobile', models.CharField(max_length=20)),
                ('theme', models.IntegerField(choices=[(1, 'Theme 1'), (2, 'Theme 2'), (3, 'Theme 3'), (4, 'Theme 4'), (5, 'Theme 5')], default=1)),
                ('description', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('description3', models.TextField(blank=True)),
                ('description4', models.TextField(blank=True)),
                ('description5', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_full_payment', models.BooleanField(default=True)),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('allow_cash_on_delivery', models.BooleanField(default=False)),
                ('payment_required_percentage', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('cod', 'Cash on Delivery'), ('bank', 'Bank Transfer'), ('wallet', 'E-Wallet'), ('hawala', 'Hawala / حوالة'), ('other', 'Other')], default='other', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
