# Generated by Django 4.2.15 on 2025-12-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hero_fit',
            field=models.CharField(choices=[('contain', 'احتواء (بدون قص)'), ('cover', 'ملء (مع قص)')], default='contain', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='hero_height',
            field=models.PositiveIntegerField(default=350, help_text='ارتفاع صورة الهيرو بالبكسل'),
        ),
    ]
