# Generated by Django 4.2.15 on 2026-01-08 06:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_hero_fit_store_hero_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cashback_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة الكاش باك من ربح الطلب (مثال: 5 = 5%)', max_digits=5),
        ),
    ]
