# Generated by Django 4.2.15 on 2026-01-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_cashback_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rkmdb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='rkmtb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
