# Generated by Django 4.2.15 on 2026-02-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_rkmdb_store_rkmtb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
