# Generated by Django 4.2.15 on 2026-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storepaymentmethod',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storepaymentmethod',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
