# Generated by Django 4.2.15 on 2026-05-14 09:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_sales_pause_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='معرف/رقم المستودع ضمن التاجر', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة (مثال: 5 = 5%)', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='stores.store')),
            ],
            options={
                'ordering': ['store_id', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('store', 'identifier'), name='unique_warehouse_identifier_per_store'),
        ),
    ]
