# Generated by Django 4.2.15 on 2026-05-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_warehouse_percentage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_warehouse_name_per_store'),
        ),
    ]
