# Generated by Django 4.2.15 on 2026-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_warehouse_unique_warehouse_name_per_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
