# Generated by Django 4.2.15 on 2026-05-14 10:15

from decimal import Decimal
from django.db import migrations, models


def backfill_main_warehouses(apps, schema_editor):
    Store = apps.get_model("stores", "Store")
    Warehouse = apps.get_model("stores", "Warehouse")

    main_name = getattr(Warehouse, "MAIN_WAREHOUSE_NAME", "المستودع الرئيسي")

    for store in Store.objects.all():
        existing = list(Warehouse.objects.filter(store=store).order_by("id"))

        main_candidates = [w for w in existing if (w.name or "").strip() == main_name]
        if main_candidates:
            main = main_candidates[0]
            if not main.is_main:
                Warehouse.objects.filter(pk=main.pk).update(is_main=True, name=main_name)
            for w in main_candidates[1:]:
                if w.is_main:
                    Warehouse.objects.filter(pk=w.pk).update(is_main=False)
            continue

        # No main warehouse: create one
        identifiers = {w.identifier for w in existing if w.identifier}
        identifier = "main"
        if identifier in identifiers:
            i = 2
            while f"main-{i}" in identifiers:
                i += 1
            identifier = f"main-{i}"

        Warehouse.objects.create(
            store=store,
            is_main=True,
            identifier=identifier,
            name=main_name,
            percentage=Decimal("0.00"),
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_warehouse_access_id_warehouse_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_main_warehouses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('store',), name='unique_main_warehouse_per_store'),
        ),
    ]
