# Generated by Django 4.2.15 on 2026-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_warehouse_is_main_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(check=models.Q(('is_main', False), ('name', 'المستودع الرئيسي'), _connector='OR'), name='main_warehouse_name_fixed'),
        ),
    ]
