# Generated by Django 4.2.15 on 2026-05-14 10:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_warehouse_main_warehouse_name_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة (مثال: 5 = 5%)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
