# Generated by Django 4.2.15 on 2026-08-23 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_unit2_pieces'),
        ('accounts', '0023_customer_optional_phone_unique_when_exists'),
        ('stores', '0019_warehouse_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.BigIntegerField(blank=True, null=True)),
                ('access_id', models.BigIntegerField(blank=True, null=True)),
                ('registered_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actual_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, null=True)),
                ('adjusted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_store_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to='accounts.storeuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='stores.store')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='stores.warehouse')),
            ],
            options={
                'ordering': ['-adjusted_at', '-id'],
            },
        ),
    ]
