# Generated by Django 4.2.15 on 2025-12-12 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen_by_store', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد')], default='pending', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء')], default='sale', max_length=10)),
                ('payment_method_name', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_recipient_name', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_account_info', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_additional_info', models.TextField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('full', 'تحويل كامل'), ('partial', 'دفعة مسبقة + باقي عند التسليم'), ('cod', 'الدفع عند الاستلام')], max_length=20, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_proof_image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.customer')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_payment', to='stores.storepaymentmethod')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('direction', models.IntegerField(default=-1)),
                ('item_note', models.TextField(blank=True, null=True, verbose_name='ملاحظات المنتج')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, help_text='تكلفة القطعة وقت البيع / سعر الشراء', max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
