# Generated by Django 4.2.15 on 2025-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accounting_invoice_number',
            field=models.IntegerField(blank=True, help_text='رقم الفاتورة في برنامج المحاسبة', null=True),
        ),
    ]
