# Generated by Django 4.2.15 on 2026-02-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_accounting_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_kind',
            field=models.SmallIntegerField(choices=[(1, 'Invoice'), (2, 'Notice')], default=1, help_text='1 = فاتورة, 2 = إشعار قبض/صرف'),
        ),
    ]
