# Generated by Django 4.2.15 on 2026-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='update_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
