# Generated by Django 4.2.15 on 2026-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_update_time_orderitem_access_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('full', 'طھط\xadظˆظٹظ„ ظƒط§ظ…ظ„'), ('partial', 'ط¯ظپط¹ط© ظ…ط³ط¨ظ‚ط© + ط¨ط§ظ‚ظٹ ط¹ظ†ط¯ ط§ظ„طھط³ظ„ظٹظ…'), ('cod', 'ط§ظ„ط¯ظپط¹ ط¹ظ†ط¯ ط§ظ„ط§ط³طھظ„ط§ظ…')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'ظ‚ظٹط¯ ط§ظ„ط§ظ†طھط¸ط§ط±'), ('confirmed', 'طھظ… ط§ظ„طھط£ظƒظٹط¯')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'ط¨ظٹط¹'), ('purchase', 'ط´ط±ط§ط،')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='طھظƒظ„ظپط© ط§ظ„ظ‚ط·ط¹ط© ظˆظ‚طھ ط§ظ„ط¨ظٹط¹ / ط³ط¹ط± ط§ظ„ط´ط±ط§ط،', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='direction',
            field=models.IntegerField(default=-1, help_text='ط¨ظٹط¹ = -1 / ط´ط±ط§ط، = +1'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_note',
            field=models.TextField(blank=True, null=True, verbose_name='ظ…ظ„ط§ط\xadط¸ط§طھ ط§ظ„ظ…ظ†طھط¬'),
        ),
    ]
