# Generated by Django 4.2.15 on 2026-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_payment_type_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='warehouse_access_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
