# Generated by Django 4.2.15 on 2026-05-14 16:17

from django.db import migrations, models
import django.db.models.deletion


def backfill_orderitem_warehouse(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    Warehouse = apps.get_model("stores", "Warehouse")
    # If we have a stored numeric warehouse_access_id and it matches a Warehouse.pk, use it.
    for item in OrderItem.objects.filter(warehouse__isnull=True).iterator():
        wh_id = getattr(item, "warehouse_access_id", None)
        if wh_id in (None, 0, ""):
            continue
        wh = Warehouse.objects.filter(pk=wh_id).first()
        if wh:
            OrderItem.objects.filter(pk=item.pk).update(warehouse=wh)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_warehouse_percentage'),
        ('orders', '0011_orderitem_warehouse_access_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='stores.warehouse'),
        ),
        migrations.RunPython(backfill_orderitem_warehouse, migrations.RunPython.noop),
    ]
