# Generated by Django 4.2.15 on 2026-05-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_warehouse_percentage'),
        ('orders', '0012_orderitem_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='warehouse_access_id',
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.warehouse'),
        ),
    ]
