# Generated by Django 4.2.15 on 2026-05-14

from django.db import migrations


def backfill_order_warehouse(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    Warehouse = apps.get_model("stores", "Warehouse")

    # 1) Fill Order.warehouse for old orders (default to main warehouse per store).
    store_ids = (
        Order.objects.filter(warehouse__isnull=True)
        .values_list("store_id", flat=True)
        .distinct()
    )
    for store_id in store_ids:
        main_wh = Warehouse.objects.filter(store_id=store_id, is_main=True).first()
        if not main_wh:
            main_wh = Warehouse.objects.filter(store_id=store_id).first()
        if not main_wh:
            continue
        Order.objects.filter(store_id=store_id, warehouse__isnull=True).update(warehouse_id=main_wh.id)

    # 2) Fill OrderItem.warehouse from its parent Order.warehouse.
    for order in Order.objects.exclude(warehouse__isnull=True).only("id", "warehouse_id").iterator():
        OrderItem.objects.filter(order_id=order.id, warehouse__isnull=True).update(warehouse_id=order.warehouse_id)


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_remove_orderitem_warehouse_access_id_order_warehouse"),
    ]

    operations = [
        migrations.RunPython(backfill_order_warehouse, migrations.RunPython.noop),
    ]

