# Generated by Django 4.2.15 on 2026-05-14

from django.db import migrations


def backfill_order_created_by(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Store = apps.get_model("stores", "Store")

    # For legacy orders created before `created_by` existed, default to store owner.
    store_ids = (
        Order.objects.filter(created_by__isnull=True)
        .values_list("store_id", flat=True)
        .distinct()
    )
    for store_id in store_ids:
        owner_id = Store.objects.filter(pk=store_id).values_list("owner_id", flat=True).first()
        if owner_id:
            Order.objects.filter(store_id=store_id, created_by__isnull=True).update(created_by_id=owner_id)


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_order_created_by"),
    ]

    operations = [
        migrations.RunPython(backfill_order_created_by, migrations.RunPython.noop),
    ]

