# Generated by Django 4.2.15 on 2026-06-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_appupdate_prices_version_and_more'),
        ('orders', '0017_order_created_by_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_by_store_user',
            field=models.ForeignKey(blank=True, help_text='رقم المستخدم الداخلي (StoreUser.id) الذي أنشأ الطلب ليتطابق مع الرقم الذي يصل إلى Access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders_store', to='accounts.storeuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('full', 'تحويل كامل'), ('partial', 'دفعة مسبقة + باقي عند التسليم'), ('cod', 'الدفع عند الاستلام')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء')], default='sale', max_length=10),
        ),
    ]
