# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_created_by_store_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_local_order_id',
            field=models.IntegerField(blank=True, null=True, help_text='رقم الفاتورة المحلي داخل التطبيق'),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_sync_client_id',
            field=models.CharField(blank=True, help_text='معرف ثابت للتطبيق الذي أنشأ الفاتورة', max_length=80, null=True),
        ),
    ]
