# Generated by Django 4.2.15 on 2026-08-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_merge_0018_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء'), ('sale_return', 'مرتجع بيع'), ('purchase_return', 'مرتجع شراء')], default='sale', max_length=20),
        ),
    ]
