# Generated by Django 4.2.15 on 2025-12-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_unique_category_name_per_store'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_product_name_per_store'),
        ),
    ]
